targets:
  $default:
    builders:
      dart_mappable:
        generate_for:
          - lib/components/task/task.dart
          - lib/components/autobot_config.dart
          # - lib/autobot.dart

        options:
          # exclude: []
          include:
            [
              MetaNode,
              AskStep,
              VariablesStep,
              ReadStep,
              JavascriptStep,
              CommandStep,
              WriteStep,
              RunTaskStep,
              AutobotConfig,
            ]
          caseStyle: camelCase
          enumCaseStyle: camelCase
          ignoreNull: true
          discriminatorKey: isOfType
