targets:
  $default:
    builders:
      dart_mappable:
        generate_for:
          - lib/commands/run/models/template.dart
          # - lib/autobot.dart

        options:
          # exclude: []
          include:
            [
              MetaNode,
              AskStep,
              VariablesStep,
              ReadStep,
              JavascriptStep,
              ShellScriptStep,
              WriteStep,
              RunTaskStep,
            ]
          caseStyle: camelCase
          enumCaseStyle: camelCase
          ignoreNull: true
          discriminatorKey: isOfType
