name: autobot
description: A command line tool for automating common developer tasks like generate files, manage environment, configure projects and setup CI.
version: 0.5.3
repository: https://github.com/DeveloperZoneIO/autobot

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  args: ^2.3.0
  cli_script: ^0.2.3+1
  dart_mappable: ^0.8.7
  dcli: ^1.14.1
  equatable: ^2.0.3
  mustache_template: ^2.0.0
  path: ^1.8.0
  super_annotations: ^0.3.6
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.5
  lints: ^1.0.0
  test: ^1.16.0

executables:
  autobot:
