# This is a basic workflow to help you get started with Actions

name: release

on:
  push:
    tags:
      - "Release-*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Remove dark-mode image from README
        run: |
          tail -n +2 "README.md" > "README.tmp" && mv "README.tmp" "README.md"

      - name: Test autobot
        run: brew tap dart-lang/dart && brew install dart && dart test

      # Uploads the autobot package to pub.dev
      - name: Publish autobot to pub.dev
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.PUB_DEV_UPLOAD_CREDENTIALS_JSON }}
          flutter_package: false
          skip_test: true
          dry_run: false
